-- ============================================
-- BASIC INSTITUTIONS SEED
-- ============================================
-- Run this file after database/institutions_schema.sql

INSERT INTO institutions (
    code,
    name_ar,
    name_he,
    name_en,
    institution_type,
    city_ar,
    city_he,
    city_en,
    region,
    description_ar,
    description_he,
    description_en,
    website_url,
    latitude,
    longitude,
    is_active
)
VALUES
    (
        'bgu',
        'جامعة بن غوريون في النقب',
        'אוניברסיטת בן-גוריון בנגב',
        'Ben-Gurion University of the Negev',
        'university',
        'بئر السبع',
        'באר שבע',
        'Beer Sheva',
        'south',
        'جامعة بحثية مركزية في الجنوب، قوية في الهندسة، الطب، وعلوم الحاسوب.',
        'אוניברסיטת מחקר מרכזית בדרום, חזקה בהנדסה, רפואה ומדעי המחשב.',
        'A leading research university in the south with strong engineering, medicine, and computer science programs.',
        'https://www.bgu.ac.il',
        31.261000,
        34.799000,
        true
    ),
    (
        'sce',
        'كلية سامي شمعون للهندسة',
        'המכללה האקדמית להנדסה סמי שמעון',
        'Sami Shamoon College of Engineering',
        'engineering_college',
        'بئر السبع',
        'באר שבע',
        'Beer Sheva',
        'south',
        'كلية هندسة معروفة في الجنوب وملائمة لمسارات التكنولوجيا والهندسة التطبيقية.',
        'מכללת הנדסה מוכרת בדרום המתאימה למסלולי טכנולוגיה והנדסה יישומית.',
        'A well-known engineering college in the south, suitable for technology and applied engineering paths.',
        'https://www.sce.ac.il',
        31.245800,
        34.812700,
        true
    ),
    (
        'sapir',
        'كلية سابير الأكاديمية',
        'המכללה האקדמית ספיר',
        'Sapir Academic College',
        'academic_college',
        'شاعر هنيغف',
        'שער הנגב',
        'Shaar HaNegev',
        'south',
        'كلية أكاديمية متعددة المجالات في الجنوب وتناسب الإعلام، الإدارة، والمجالات الاجتماعية.',
        'מכללה אקדמית רב-תחומית בדרום המתאימה לתקשורת, ניהול ומדעי החברה.',
        'A multidisciplinary academic college in the south suited for media, management, and social fields.',
        'https://www.sapir.ac.il',
        31.513500,
        34.595900,
        true
    ),
    (
        'achva',
        'كلية أخفا الأكاديمية',
        'המכללה האקדמית אחוה',
        'Achva Academic College',
        'education_college',
        'קרית מלאכי',
        'קריית מלאכי',
        'Kiryat Malakhi',
        'south',
        'مؤسسة مناسبة لمسارات التربية، العلوم الاجتماعية، وبعض البرامج متعددة التخصصات.',
        'מוסד המתאים למסלולי חינוך, מדעי החברה ותוכניות רב-תחומיות.',
        'An institution suited to education, social sciences, and multidisciplinary programs.',
        'https://new.achva.ac.il',
        31.733400,
        34.746100,
        true
    ),
    (
        'kaye',
        'كلية كي للتربية',
        'המכללה האקדמית לחינוך ע"ש קיי',
        'Kaye Academic College of Education',
        'education_college',
        'بئر السبع',
        'באר שבע',
        'Beer Sheva',
        'south',
        'كلية متخصصة في إعداد المعلمين والتربية في منطقة الجنوب.',
        'מכללה המתמחה בהכשרת מורים וחינוך באזור הדרום.',
        'A college focused on teacher training and education in the south.',
        'https://kaye.ac.il',
        31.258900,
        34.791400,
        true
    ),
    (
        'open_university',
        'الجامعة المفتوحة في إسرائيل',
        'האוניברסיטה הפתוחה',
        'The Open University of Israel',
        'open_university',
        'عدة مدن',
        'מספר ערים',
        'Multiple Campuses',
        'multiple',
        'جامعة مرنة للدراسة من عدة مناطق مع مسارات مناسبة للطلاب الذين يحتاجون مرونة.',
        'אוניברסיטה גמישה ללימודים במספר אזורים עם מסלולים המתאימים לסטודנטים הזקוקים לגמישות.',
        'A flexible university with multiple study centers, suitable for students who need adaptable learning.',
        'https://www.openu.ac.il',
        NULL,
        NULL,
        true
    ),
    (
        'hebrew_university',
        'الجامعة العبرية في القدس',
        'האוניברסיטה העברית בירושלים',
        'Hebrew University of Jerusalem',
        'university',
        'القدس',
        'ירושלים',
        'Jerusalem',
        'jerusalem',
        'جامعة رائدة في البحث الأكاديمي وتقدم برامج قوية في العلوم، الطب، والإنسانيات.',
        'אוניברסיטה מובילה במחקר אקדמי עם תוכניות חזקות במדעים, רפואה ומדעי הרוח.',
        'A leading research university with strong programs in sciences, medicine, and humanities.',
        'https://new.huji.ac.il',
        31.776700,
        35.197000,
        true
    ),
    (
        'tau',
        'جامعة تل أبيب',
        'אוניברסיטת תל אביב',
        'Tel Aviv University',
        'university',
        'تل أبيب',
        'תל אביב',
        'Tel Aviv',
        'tel_aviv',
        'جامعة كبيرة ومتنوعة مع برامج قوية في التكنولوجيا، الإدارة، والعلوم الصحية.',
        'אוניברסיטה גדולה ומגוונת עם תוכניות חזקות בטכנולוגיה, ניהול ומדעי הבריאות.',
        'A large and diverse university with strong technology, management, and health programs.',
        'https://www.tau.ac.il',
        32.113300,
        34.804400,
        true
    ),
    (
        'technion',
        'التخنيون - المعهد الإسرائيلي للتكنولوجيا',
        'הטכניון - מכון טכנולוגי לישראל',
        'Technion - Israel Institute of Technology',
        'university',
        'حيفا',
        'חיפה',
        'Haifa',
        'haifa',
        'مؤسسة رائدة جدًا في الهندسة، التكنولوجيا، والعلوم الدقيقة.',
        'מוסד מוביל במיוחד בהנדסה, טכנולוגיה ומדעים מדויקים.',
        'A premier institution for engineering, technology, and exact sciences.',
        'https://www.technion.ac.il',
        32.776900,
        35.021500,
        true
    ),
    (
        'bar_ilan',
        'جامعة بار إيلان',
        'אוניברסיטת בר-אילן',
        'Bar-Ilan University',
        'university',
        'رمات غان',
        'רמת גן',
        'Ramat Gan',
        'center',
        'جامعة معروفة ببرامجها في علوم الحاسوب، التربية، والعلوم الاجتماعية.',
        'אוניברסיטה מוכרת עם תוכניות טובות במדעי המחשב, חינוך ומדעי החברה.',
        'A recognized university with strong programs in computer science, education, and social sciences.',
        'https://www.biu.ac.il',
        32.072800,
        34.843300,
        true
    ),
    (
        'haifa_university',
        'جامعة حيفا',
        'אוניברסיטת חיפה',
        'University of Haifa',
        'university',
        'حيفا',
        'חיפה',
        'Haifa',
        'haifa',
        'جامعة متعددة المجالات مع حضور قوي في التربية، العلوم الاجتماعية، والإدارة.',
        'אוניברסיטה רב-תחומית עם נוכחות חזקה בחינוך, מדעי החברה וניהול.',
        'A multidisciplinary university with strong education, social sciences, and management offerings.',
        'https://www.haifa.ac.il',
        32.762500,
        35.017300,
        true
    ),
    (
        'ariel',
        'جامعة أريئيل',
        'אוניברסיטת אריאל',
        'Ariel University',
        'university',
        'أريئيل',
        'אריאל',
        'Ariel',
        'center',
        'جامعة تقدم برامج في الهندسة، العلوم الصحية، والعلوم الاجتماعية.',
        'אוניברסיטה המציעה תוכניות בהנדסה, מדעי הבריאות ומדעי החברה.',
        'A university offering engineering, health sciences, and social science programs.',
        'https://www.ariel.ac.il',
        32.106400,
        35.184800,
        true
    ),
    (
        'reichman',
        'جامعة رايخمان',
        'אוניברסיטת רייכמן',
        'Reichman University',
        'university',
        'هرتسليا',
        'הרצליה',
        'Herzliya',
        'center',
        'جامعة خاصة مع برامج معروفة في الحاسوب، ريادة الأعمال، والإدارة.',
        'אוניברסיטה פרטית עם תוכניות מוכרות במדעי המחשב, יזמות וניהול.',
        'A private university known for computer science, entrepreneurship, and management.',
        'https://www.runi.ac.il',
        32.164600,
        34.836600,
        true
    ),
    (
        'hit',
        'معهد حولون للتكنولوجيا',
        'המכון הטכנולוגי חולון',
        'Holon Institute of Technology',
        'engineering_college',
        'حولون',
        'חולון',
        'Holon',
        'center',
        'معهد تطبيقي مناسب للتكنولوجيا، التصميم، والهندسة.',
        'מכון יישומי המתאים לטכנולוגיה, עיצוב והנדסה.',
        'An applied institute suitable for technology, design, and engineering.',
        'https://www.hit.ac.il',
        32.015900,
        34.773600,
        true
    ),
    (
        'afeka',
        'كلية أفيكا للهندسة',
        'המכללה האקדמית להנדסה אפקה',
        'Afeka Academic College of Engineering',
        'engineering_college',
        'تل أبيب',
        'תל אביב',
        'Tel Aviv',
        'tel_aviv',
        'كلية هندسة مناسبة للطلاب الذين يريدون مسارًا تطبيقيًا في قلب منطقة التكنولوجيا.',
        'מכללת הנדסה המתאימה לסטודנטים שרוצים מסלול יישומי בלב אזור הטכנולוגיה.',
        'An engineering college suited to students seeking an applied path in the heart of the tech region.',
        'https://www.afeka.ac.il',
        32.115700,
        34.817900,
        true
    )
ON CONFLICT (code) DO UPDATE SET
    name_ar = EXCLUDED.name_ar,
    name_he = EXCLUDED.name_he,
    name_en = EXCLUDED.name_en,
    institution_type = EXCLUDED.institution_type,
    city_ar = EXCLUDED.city_ar,
    city_he = EXCLUDED.city_he,
    city_en = EXCLUDED.city_en,
    region = EXCLUDED.region,
    description_ar = EXCLUDED.description_ar,
    description_he = EXCLUDED.description_he,
    description_en = EXCLUDED.description_en,
    website_url = EXCLUDED.website_url,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

INSERT INTO institution_programs (
    institution_id,
    major_key,
    program_name_ar,
    program_name_he,
    program_name_en,
    field_category,
    degree_type,
    description_ar,
    description_he,
    description_en,
    admission_notes_ar,
    admission_notes_he,
    admission_notes_en
)
VALUES
    ((SELECT id FROM institutions WHERE code = 'bgu'), 'computer_science', 'علوم الحاسوب', 'מדעי המחשב', 'Computer Science', 'technology', 'bachelor', 'برنامج قوي في الحاسوب والبرمجة.', 'תוכנית חזקה במדעי המחשב ותכנות.', 'A strong computer science and programming program.', 'يفضل رياضيات قوية وإنجليزية جيدة.', 'מומלץ רקע טוב במתמטיקה ואנגלית.', 'Strong math and English are recommended.'),
    ((SELECT id FROM institutions WHERE code = 'bgu'), 'medicine', 'الطب', 'רפואה', 'Medicine', 'health', 'doctorate', 'مسار طبي متقدم في الجنوب.', 'מסלול רפואי מתקדם בדרום.', 'An advanced medical track in the south.', 'يحتاج تحصيلًا عاليًا في العلوم.', 'נדרש הישג גבוה במדעים.', 'High science achievement is needed.'),
    ((SELECT id FROM institutions WHERE code = 'sce'), 'engineering', 'هندسة البرمجيات', 'הנדסת תוכנה', 'Software Engineering', 'engineering', 'bachelor', 'مسار تطبيقي قوي في البرمجيات.', 'מסלול יישומי חזק בתוכנה.', 'A strong applied software track.', 'رياضيات 4 أو 5 وحدات مفيدة.', '4 או 5 יחידות מתמטיקה מועילות.', '4 or 5 math units are helpful.'),
    ((SELECT id FROM institutions WHERE code = 'sce'), 'engineering', 'الهندسة الكهربائية', 'הנדסת חשמל', 'Electrical Engineering', 'engineering', 'bachelor', 'برنامج مناسب لمحبي الإلكترونيات والطاقة.', 'תוכנית המתאימה לחובבי אלקטרוניקה ואנרגיה.', 'Suited for students interested in electronics and energy.', 'خلفية جيدة في الفيزياء مهمة.', 'רקע טוב בפיזיקה חשוב.', 'A solid physics background is important.'),
    ((SELECT id FROM institutions WHERE code = 'sapir'), 'business', 'إدارة الأعمال', 'מנהל עסקים', 'Business Administration', 'business', 'bachelor', 'برنامج عملي في الإدارة والاقتصاد.', 'תוכנית מעשית בניהול וכלכלה.', 'A practical management and economics program.', 'اللغة والرياضيات تساعد في النجاح.', 'שפה ומתמטיקה מסייעות להצלחה.', 'Language and math skills help.'),
    ((SELECT id FROM institutions WHERE code = 'sapir'), 'education', 'الاتصال والإعلام', 'תקשורת', 'Communication', 'social_sciences', 'bachelor', 'ملائم للطلاب ذوي الاهتمام بالإعلام والمجتمع.', 'מתאים לסטודנטים בעלי עניין בתקשורת וחברה.', 'Suitable for students interested in media and society.', 'يفضل قدرة جيدة على التعبير.', 'מומלצת יכולת הבעה טובה.', 'Good expression skills are recommended.'),
    ((SELECT id FROM institutions WHERE code = 'achva'), 'education', 'التربية', 'חינוך', 'Education', 'education', 'bachelor', 'برنامج يركز على التعليم والعمل مع الطلاب.', 'תוכנית המתמקדת בהוראה ובעבודה עם תלמידים.', 'Focused on teaching and working with students.', 'الميل للتواصل والصبر مهم.', 'חשובה נטייה לתקשורת וסבלנות.', 'Communication and patience matter.'),
    ((SELECT id FROM institutions WHERE code = 'kaye'), 'education', 'التربية والتعليم', 'חינוך והוראה', 'Education and Teaching', 'education', 'bachelor', 'إعداد معلمين للمدارس ومجالات التربية.', 'הכשרת מורים לבתי ספר ולתחומי חינוך.', 'Teacher preparation for schools and education fields.', 'مناسب لمن يحب الشرح والعمل مع الأطفال.', 'מתאים למי שאוהב להסביר ולעבוד עם ילדים.', 'Great for students who like explaining and working with children.'),
    ((SELECT id FROM institutions WHERE code = 'open_university'), 'computer_science', 'علوم الحاسوب', 'מדעי המחשב', 'Computer Science', 'technology', 'bachelor', 'مسار مرن يمكن دمجه مع العمل أو ظروف خاصة.', 'מסלול גמיש שניתן לשלב עם עבודה או נסיבות מיוחדות.', 'A flexible path that can be combined with work or special circumstances.', 'يلائم الطلاب الذين يحتاجون مرونة زمنية.', 'מתאים לסטודנטים הזקוקים לגמישות בזמן.', 'Suitable for students who need schedule flexibility.'),
    ((SELECT id FROM institutions WHERE code = 'hebrew_university'), 'medicine', 'الطب', 'רפואה', 'Medicine', 'health', 'doctorate', 'برنامج طبي أكاديمي قوي.', 'תוכנית רפואית אקדמית חזקה.', 'A strong academic medicine program.', 'يحتاج أساسًا علميًا ممتازًا.', 'נדרש בסיס מדעי מצוין.', 'Excellent science preparation is needed.'),
    ((SELECT id FROM institutions WHERE code = 'tau'), 'computer_science', 'علوم الحاسوب', 'מדעי המחשב', 'Computer Science', 'technology', 'bachelor', 'برنامج متقدم في البرمجة والأنظمة.', 'תוכנית מתקדמת בתכנות ומערכות.', 'An advanced program in programming and systems.', 'الرياضيات والإنجليزية مهمتان.', 'מתמטיקה ואנגלית חשובות.', 'Math and English are important.'),
    ((SELECT id FROM institutions WHERE code = 'technion'), 'engineering', 'الهندسة الميكانيكية', 'הנדסת מכונות', 'Mechanical Engineering', 'engineering', 'bachelor', 'برنامج هندسي قوي جدًا للطلاب المتفوقين.', 'תוכנית הנדסית חזקה מאוד לסטודנטים מצטיינים.', 'A very strong engineering program for high-achieving students.', 'يفضل مستوى عالٍ في الرياضيات والفيزياء.', 'מומלץ רמה גבוהה במתמטיקה ובפיזיקה.', 'High-level math and physics are recommended.'),
    ((SELECT id FROM institutions WHERE code = 'bar_ilan'), 'computer_science', 'علوم الحاسوب', 'מדעי המחשב', 'Computer Science', 'technology', 'bachelor', 'برنامج معروف في الحاسوب والبيانات.', 'תוכנית מוכרת במדעי המחשב ונתונים.', 'A recognized program in computing and data.', 'يناسب الطلاب ذوي التفكير المنطقي.', 'מתאים לסטודנטים בעלי חשיבה לוגית.', 'Suitable for logical thinkers.'),
    ((SELECT id FROM institutions WHERE code = 'haifa_university'), 'business', 'إدارة الأعمال', 'מנהל עסקים', 'Business Administration', 'business', 'bachelor', 'برنامج في الإدارة والتنظيم وسوق العمل.', 'תוכנית בניהול, ארגון ושוק העבודה.', 'A program in management, organization, and the job market.', 'مفيد لمن يحب القيادة واتخاذ القرار.', 'מתאים למי שאוהב הנהגה וקבלת החלטות.', 'Useful for students who like leadership and decisions.'),
    ((SELECT id FROM institutions WHERE code = 'ariel'), 'engineering', 'الهندسة المدنية', 'הנדסה אזרחית', 'Civil Engineering', 'engineering', 'bachelor', 'برنامج يربط بين الرياضيات والتصميم والبناء.', 'תוכנית המחברת בין מתמטיקה, תכנון ובנייה.', 'Connects math, design, and construction.', 'الفيزياء والرياضيات مهمتان للمسار.', 'פיזיקה ומתמטיקה חשובות למסלול.', 'Physics and math are important here.'),
    ((SELECT id FROM institutions WHERE code = 'reichman'), 'business', 'إدارة الأعمال', 'מנהל עסקים', 'Business Administration', 'business', 'bachelor', 'برنامج حديث يركز على الإدارة وريادة الأعمال.', 'תוכנית מודרנית המתמקדת בניהול ויזמות.', 'A modern program focused on management and entrepreneurship.', 'مفيد لمن لديه دافع قيادي واهتمام بالأعمال.', 'מתאים לבעלי יוזמה ועניין בעסקים.', 'Great for students with initiative and business interest.'),
    ((SELECT id FROM institutions WHERE code = 'hit'), 'engineering', 'تكنولوجيا التصميم', 'טכנולוגיות עיצוב', 'Design Technology', 'design', 'bachelor', 'برنامج يجمع بين التكنولوجيا والتصميم.', 'תוכנית המשלבת טכנולוגיה ועיצוב.', 'Combines technology with design.', 'يناسب من يحب الإبداع مع الجانب التقني.', 'מתאים למי שאוהב יצירתיות עם צד טכנולוגי.', 'Fits creative students with a technical side.'),
    ((SELECT id FROM institutions WHERE code = 'afeka'), 'engineering', 'هندسة البرمجيات', 'הנדסת תוכנה', 'Software Engineering', 'engineering', 'bachelor', 'كلية مناسبة لمسار هندسي تطبيقي في وسط البلاد.', 'מכללה המתאימה למסלול הנדסי יישומי במרכז הארץ.', 'Suited to an applied engineering path in central Israel.', 'الاستعداد الجيد في الرياضيات يساعد.', 'הכנה טובה במתמטיקה מסייעת.', 'Good math preparation helps.')
ON CONFLICT (institution_id, program_name_en) DO UPDATE SET
    major_key = EXCLUDED.major_key,
    field_category = EXCLUDED.field_category,
    degree_type = EXCLUDED.degree_type,
    description_ar = EXCLUDED.description_ar,
    description_he = EXCLUDED.description_he,
    description_en = EXCLUDED.description_en,
    admission_notes_ar = EXCLUDED.admission_notes_ar,
    admission_notes_he = EXCLUDED.admission_notes_he,
    admission_notes_en = EXCLUDED.admission_notes_en,
    updated_at = NOW();

INSERT INTO major_institution_matches (
    major_key,
    institution_id,
    match_priority,
    weight,
    notes_ar,
    notes_he,
    notes_en,
    is_featured
)
VALUES
    ('computer_science', (SELECT id FROM institutions WHERE code = 'bgu'), 1, 1.00, 'مؤسسة قوية جدًا للحاسوب في الجنوب.', 'מוסד חזק מאוד למדעי המחשב בדרום.', 'A very strong southern choice for computer science.', true),
    ('computer_science', (SELECT id FROM institutions WHERE code = 'tau'), 2, 0.96, 'مناسبة للطلاب ذوي النتائج العالية في المنطق والإنجليزية.', 'מתאים לתלמידים עם ציונים גבוהים בלוגיקה ובאנגלית.', 'Well-suited for students with strong logic and English.', true),
    ('computer_science', (SELECT id FROM institutions WHERE code = 'bar_ilan'), 3, 0.92, 'خيار أكاديمي جيد في المركز.', 'אפשרות אקדמית טובה במרכז.', 'A good academic option in the center.', false),
    ('computer_science', (SELECT id FROM institutions WHERE code = 'open_university'), 4, 0.88, 'خيار مرن لمن يحتاج جدولًا قابلًا للتكيّف.', 'אפשרות גמישה למי שצריך לוח זמנים מותאם.', 'A flexible option for students needing schedule adaptability.', false),
    ('engineering', (SELECT id FROM institutions WHERE code = 'technion'), 1, 1.00, 'من أقوى الخيارات للهندسة في إسرائيل.', 'אחת האפשרויות החזקות ביותר להנדסה בישראל.', 'One of the strongest engineering choices in Israel.', true),
    ('engineering', (SELECT id FROM institutions WHERE code = 'sce'), 2, 0.96, 'مناسب جدًا لمسارات الهندسة التطبيقية في الجنوب.', 'מתאים מאוד למסלולי הנדסה יישומית בדרום.', 'A great fit for applied engineering paths in the south.', true),
    ('engineering', (SELECT id FROM institutions WHERE code = 'bgu'), 3, 0.93, 'خيار بحثي وأكاديمي قوي.', 'בחירה מחקרית ואקדמית חזקה.', 'A strong research-oriented engineering choice.', false),
    ('engineering', (SELECT id FROM institutions WHERE code = 'afeka'), 4, 0.89, 'خيار جيد في المركز للطلاب التقنيين.', 'אפשרות טובה במרכז לסטודנטים טכנולוגיים.', 'A good central option for technical students.', false),
    ('medicine', (SELECT id FROM institutions WHERE code = 'bgu'), 1, 1.00, 'مناسب للطلاب ذوي القوة العالية في العلوم والطب.', 'מתאים לתלמידים עם חוזקה גבוהה במדעים וברפואה.', 'Suited to students with strong science and medical potential.', true),
    ('medicine', (SELECT id FROM institutions WHERE code = 'hebrew_university'), 2, 0.97, 'خيار أكاديمي قوي جدًا للطب.', 'בחירה אקדמית חזקה מאוד לרפואה.', 'A very strong academic medicine option.', true),
    ('medicine', (SELECT id FROM institutions WHERE code = 'technion'), 3, 0.95, 'مناسب للمستويات العلمية العالية.', 'מתאים לרמות מדעיות גבוהות.', 'Well-suited for high scientific achievement.', false),
    ('nursing', (SELECT id FROM institutions WHERE code = 'bgu'), 1, 0.97, 'ملائم للطلاب ذوي الاهتمام بالمجال الصحي والخدمة.', 'מתאים לתלמידים עם עניין בתחום הבריאות והסיוע.', 'A strong match for students interested in health and service.', true),
    ('nursing', (SELECT id FROM institutions WHERE code = 'haifa_university'), 2, 0.90, 'خيار جيد في الشمال للمجالات الصحية.', 'אפשרות טובה בצפון לתחומי הבריאות.', 'A good northern option for health-related study.', false),
    ('education', (SELECT id FROM institutions WHERE code = 'kaye'), 1, 1.00, 'خيار أساسي لطلاب التربية في الجنوب.', 'אפשרות מרכזית לסטודנטים לחינוך בדרום.', 'A core southern choice for education students.', true),
    ('education', (SELECT id FROM institutions WHERE code = 'achva'), 2, 0.95, 'مناسب للطلاب الذين يحبون التعليم والعمل مع الأطفال.', 'מתאים לסטודנטים שאוהבים הוראה ועבודה עם ילדים.', 'A good fit for students who like teaching and working with children.', true),
    ('education', (SELECT id FROM institutions WHERE code = 'open_university'), 3, 0.84, 'خيار مرن لمن يريد الدراسة مع التزامات أخرى.', 'אפשרות גמישה למי שמעוניין ללמוד לצד התחייבויות אחרות.', 'A flexible option for students balancing other commitments.', false),
    ('business', (SELECT id FROM institutions WHERE code = 'reichman'), 1, 0.96, 'مناسب للطلاب ذوي الاهتمام بالإدارة وريادة الأعمال.', 'מתאים לסטודנטים עם עניין בניהול ויזמות.', 'A strong option for students interested in management and entrepreneurship.', true),
    ('business', (SELECT id FROM institutions WHERE code = 'sapir'), 2, 0.90, 'خيار عملي قريب لطلاب الجنوب.', 'אפשרות מעשית וקרובה לתלמידי הדרום.', 'A practical nearby option for students in the south.', true),
    ('business', (SELECT id FROM institutions WHERE code = 'haifa_university'), 3, 0.88, 'خيار أكاديمي جيد في الإدارة.', 'אפשרות אקדמית טובה בניהול.', 'A solid academic management option.', false)
ON CONFLICT (major_key, institution_id) DO UPDATE SET
    match_priority = EXCLUDED.match_priority,
    weight = EXCLUDED.weight,
    notes_ar = EXCLUDED.notes_ar,
    notes_he = EXCLUDED.notes_he,
    notes_en = EXCLUDED.notes_en,
    is_featured = EXCLUDED.is_featured,
    updated_at = NOW();
